version: "3"

services:
  backend:
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}_backend
    hostname: backend
    ports:
      - "5000:5000"
    env_file:
      - app/.env
    volumes:
      - "./app:/app"
      - "/app/.venv"
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "5000",
        "--reload"
      ]
    networks:
      - vti-network

networks:
  vti-network:
    name: ${COMPOSE_PROJECT_NAME}-network
    driver: bridge
